#ifndef __PINS_H
#define __PINS_H

#define GPS_RESET_BANK GPIOA
#define GPS_RESET_PIN GPIO_PIN_0

#define STEPPER_RESET_BANK GPIOA
#define STEPPER_RESET_PIN GPIO_PIN_0

#define STEPPER_EN_BANK GPIOA
#define STEPPER_EN_PIN GPIO_PIN_0

#define STEPPER_STCK_BANK GPIOA
#define STEPPER_STCK_PIN GPIO_PIN_0

#define STEPPER_DIR_BANK GPIOA
#define STEPPER_DIR_PIN GPIO_PIN_0

#define STEPPER_MODE1_BANK GPIOA
#define STEPPER_MODE1_PIN GPIO_PIN_0

#define STEPPER_MODE2_BANK GPIOA
#define STEPPER_MODE2_PIN GPIO_PIN_0

#define STEPPER_MODE3_BANK GPIOA
#define STEPPER_MODE3_PIN GPIO_PIN_0

#endif
